import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { login } from "../services/auth";

export default function Login() {
  const [token, setToken] = useState("");
  const [error, setError] = useState("");
  const navigation = useRouter();

  const handleSubmit = (e) => {
    e.preventDefault();
    
    if (token) {
      login(token);
      navigation.push("/users");
    } else {
      setError("Token is required");
    }
  };

  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />
      <main className="text-center my-10 min-h-screen">
        <h1 className="text-2xl font-bold">
          Please, to start your jouney paste your GitHub personal access token
          here 👇
        </h1>

        <div className="flex justify-center mt-10 flex-col">
          <input
            type="text"
            className="border-2 border-gray-300 p-2 rounded-lg w-96 self-center"
            placeholder="Paste your GitHub personal access token here"
            value={token}
            onChange={(e) => setToken(e.target.value)}
          />
          {error && <p className="text-red-500">{error}</p>}
        </div>

        <button className="bg-blue-500 text-white px-10 py-2 rounded-lg mt-10" onClick={handleSubmit}>
          Go to users list!
        </button>
      </main>
      <Footer />
    </>
  );
}
