import Head from "next/head";
import { Footer } from "./Footer";
import { Header } from "./Header";

interface HomeProps {
  children: React.ReactNode;
  title: string;
}

export function Layout(props: HomeProps) {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />
      <main className="min-h-screen">{props.children}</main>
      <Footer />
    </>
  );
}
